// pdfRegistry.ts
export const ALL_PDFS: Record<string, any> = {
	BITUMEN_PDF:
		"https://drive.google.com/file/d/10zCWlS6wPiuXQ4oLaiGrd3LYtLmxnOaU/preview",
	VG30_PDF:
		"https://drive.google.com/file/d/16NPtVEIF_FQ3PE8fq4ZDmOqhgGagM2DB/preview",
	VG40_PDF:
		"https://drive.google.com/file/d/1yHnYH3SD4ElVTp3w5EAWmq1GLTQJS4sa/preview",
	GRI_150N_PDF:
		"https://drive.google.com/file/d/1trUa2hqpbdUX_2M_IfPnQC5sEtXeUZo6/preview",
	GRII_150SN_PDF:
		"https://drive.google.com/file/d/1trUa2hqpbdUX_2M_IfPnQC5sEtXeUZo6/preview",
	ATF_PDF:
		"https://drive.google.com/file/d/15WLcZftJDC-mBHhLaH_96JYEkRvswVyV/preview",
	BRF150BS_PDF:
		"https://drive.google.com/file/d/1dP7G6jKTtq4DKQjg5RUxQel_AUar7MTz/preview",
	ELASTO_SUPREME_H_PDF:
		"https://drive.google.com/file/d/1c6yLaEWLgWrFdTqRkr-BGtkINTKDsY6S/preview",
	ELASTO_SUPREME_PDF:
		"https://drive.google.com/file/d/1PCfYmLX1NpYgZXgBqWAWapTfecQndcSi/preview",
	ELASTO710_PDF:
		"https://drive.google.com/file/d/1el_3jRUItWf2zAITd48I2miYgwFLihzg/preview",
	ETHANOL_PDF:
		"https://drive.google.com/file/d/1KCiHAebR2RixzieGsTLxDz3P6VUUKtXR/preview",
	FLAME_PLUS_PDF:
		"https://drive.google.com/file/d/1H7cXRmC5yPutA-huEY5XOiRvbjIAwluF/preview",
	HEXANE_PDF:
		"https://drive.google.com/file/d/1za_EnUkoVu5wRJSreLMjUfoqyGmgdb8B/preview",
	HFHSD_PDF:
		"https://drive.google.com/file/d/1Z2nvVkqHd1Jarv-ACHJSuy7TGs_ZTRF1/preview",
	HSD_PDF:
		"https://drive.google.com/file/d/1Fpq-Ronp4JcuOLkK6h3YgoVR_HCXJYOS/preview",
	JBO_PDF:
		"https://drive.google.com/file/d/1z6HrZVEro48s_onUtDhzu8-av2kMKw8G/preview",
	LDO_PDF:
		"https://drive.google.com/file/d/1nbRH_ZPY67WdrgG6CLUiePJAeovqLCyT/preview",
	LLDPE_PDF:
		"https://drive.google.com/file/d/1vPHy_mZ6hbDufEeydo_TrM0IHHmbIcYx/preview",
	LPG_PDF:
		"https://drive.google.com/file/d/1n_FEoXe0qLVRayCEN5N9VrZPHmvx5mfE/preview",
	LSFO_LSHSFO_VLSFO_PDF:
		"https://drive.google.com/file/d/17TK8nAw54Rgzg0x9rklX2MiZnMY-mzQV/preview",
	LSHS_PDF:
		"https://drive.google.com/file/d/1uLameSLiEgZugTHIJ-X0Afv9WN5KLqon/preview",
	MS_PDF:
		"https://drive.google.com/file/d/1F1MxlDBQtm3X8_s81FQ4JUzOq6a8WJ5O/preview",
	NAPHTHA_PDF:
		"https://drive.google.com/file/d/1XseSYUB7meiCWuTwdvVvVugiiQ1Ahuq5/preview",
	PPHP_PDF:
		"https://drive.google.com/file/d/1Szsbi6agYX2f43H54bK0UbCbPdGSE_Rg/preview",
	PROPANE_BUTANE_PDF:
		"https://drive.google.com/file/d/109IbTn3Vy9ZyjKyAIwiuJFYnCEJhX3qB/preview",
	SOLVENT_1425_PDF:
		"https://drive.google.com/file/d/1U-krPb89e85GECrMkmc421EmBFtzvJx6/preview",
	SOLVENT_2445_PDF:
		"https://drive.google.com/file/d/12ydV3AOpceFvNKA-bpvk8bVoBU9PCTuW/preview",
	KEROSENE_PDF:
		"https://drive.google.com/file/d/1CVLNw7vucDCnqT-rv1Edsyg_JzmokBCn/preview",
	HOMOPOLYMER_PDF:
		"https://drive.google.com/file/d/15LP01gpzIKYkQ2jF0WPSEmzQu32KgNVz/preview",
	"500N_PDF":
		"https://drive.google.com/file/d/17rwJFvVlmgI3gBCTrASZ9jBpE117PWRi/preview",
	"500SN_PDF":
		"https://drive.google.com/file/d/1PbdiVr_WGyh-RLxDq1RlP7-PQi67NWEf/preview",
	HP_GAS_RAZOR_PDF:
		"https://drive.google.com/file/d/1HI0QV_VElQR64gpIAFnyu2IPLxPWbfn-/preview",
	PROPYLENE_PDF:
		"https://drive.google.com/file/d/1pAsaBMM8KisOmRT_VL3gOSqy_QQ39qrc/preview",
	CRMB_PDF:
		"https://drive.google.com/file/d/1ToabsezpMbOLN9ZBTZ-05JoQn4iFsgQy/preview",
	DOLPHIN_PDF:
		"https://drive.google.com/file/d/1JOl7vxYKrHVv94Z6hAh_KTbr0GOwGlGw/preview",
	//
	TIC_PDF:
		"https://drive.google.com/file/d/12f9ezZN_EEcRo0TkbVglrp6TlDmVSvc8/preview",
	VISABIT2_PDF:
		"https://drive.google.com/file/d/1bouGdUCjYYpZiVXwOqYiPUVR_SkUokiT/preview",
	THERMOPRO_W_PDF:
		"https://drive.google.com/file/d/1IXgVNnDbb4SzFPZb89oIXXfX4jMOZSmc/preview",
	THERMGAMMA_PDF:
		"https://drive.google.com/file/d/14rXpJrBZQhSAFk9rSViw9l_4wVQvSfp1/preview",
	THERMOPRO_PDF:
		"https://drive.google.com/file/d/1f2AodWJVrusg5DTK3H7y0KTVYuFU9nyd/preview",
	SHINEPRO_PDF:
		"https://drive.google.com/file/d/1j9sqCOBGieeX7Viu2R2cBEMjPx8sakcU/preview",
	PMA_PDF:
		"https://drive.google.com/file/d/1ubtc3sfJa_EYm9kSdhjBv8SNrF1qS53L/preview",
	PMA45_PDF:
		"https://drive.google.com/file/d/1UVwgkjPLxGtzByItV7Toi6x0_6xH5T36/preview",
	PPD_ULSD_PDF:
		"https://drive.google.com/file/d/1TZRaGW0WM_QyMqTB2P8E7pq2Uq7BFNbx/preview",
	SOLAROKARE_PDF:
		"https://drive.google.com/file/d/1iqJS1490rC2b0-9hanw7EN5Kii-xxXWL/preview",
	SAN_PDF:
		"https://drive.google.com/file/d/13k7_-sKegFiQ9jNOjfOzHgTBb0D_mN-s/preview",
	POWER100ADDITIVE_PDF:
		"https://drive.google.com/file/d/16t8jLqDPH_H0LqSC3xbSQHfkSC5ZpIzP/preview",
	PFT_PDF:
		"https://drive.google.com/file/d/1zC-ywQOUrqxyWglKm3CNrl2NOTWWcMVw/preview",
	PCRHDPE_PDF:
		"https://drive.google.com/file/d/1B3Su_QfbzmudE6OhTc5i0gSXWMhjLOOf/preview",
	NEUTMAX_SUE_PDF:
		"https://drive.google.com/file/d/1J_Q80mmndM_Cgp5BtO45lADFyQOj3xLE/preview",
	NEUTMAX_PDF:
		"https://drive.google.com/file/d/12VyMAOyU0ccEaJNr3TCfx_3UXnEDXqIN/preview",
	LAUNDRYSANITIZER_PDF:
		"https://drive.google.com/file/d/1Rj97h0etC7UEeQIhz2ZyoQT-6bcXTnc3/preview",
	NANOLITE_PDF:
		"https://drive.google.com/file/d/1O4eEie0_er-65cqjZ7clZPznL3yZgyai/preview",
	HP_NANO_PRIMER_PDF:
		"https://drive.google.com/file/d/18cu6Fc_AjtVEIcgqcvM1uiiFd2FGO1WF/preview",
	NANOKOOOL_PDF:
		"https://drive.google.com/file/d/1THtoPegpYC_r8m5paSvxOVttIpaAi84x/preview",
	HPDUCER_PDF:
		"https://drive.google.com/file/d/1XmL7qiSvxMFUZufCiCQ2niTzx0a_hO-K/preview",
	NANOKOAT_PDF:
		"https://drive.google.com/file/d/1LqJqfFX1nXt3OjSAsx272L7QKrT2exb4/preview",
	FUSE3D_PDF:
		"https://drive.google.com/file/d/1Lrrri8Tp_vCq_2lRaL24PhSY2gLnZZ7j/preview",
	FILMMAX_HT_PDF:
		"https://drive.google.com/file/d/1lvIJlK6XHnnXn4gQM3A5HB7PdO4oVHks/preview",
	FROSTFREE_PDF:
		"https://drive.google.com/file/d/1-7CQm1Fmur6M_pmq3NuNWmy0D6lYCbw5/preview",
	FROSTSHIELD_PDF:
		"https://drive.google.com/file/d/1LdiR16h2IwLEGKPQyRf-8Hv_3Jh3zpvW/preview",
	ENSCOUR_PDF:
		"https://drive.google.com/file/d/1F5jV0tbrdgb6YGGqLg5ujoMkdgxnSgoP/preview",
	DWA_V2_PDF:
		"https://drive.google.com/file/d/1qifUc8lTyrV2lqaQteokEE9Lj51VP0MG/preview",
	EGIN_PDF:
		"https://drive.google.com/file/d/1CL4uLAPleQalxwAn0tBJZmg2G_7g-4jc/preview",
	EASYWASH_PDF:
		"https://drive.google.com/file/d/1WG-b2OENqtpEpOg6qklQIBBovwjwgJk1/preview",
	CORRMIT_PDF:
		"https://drive.google.com/file/d/1cKnbYcvW91lYSWZrtE7vjzJ6jpKcWmCU/preview",
	DRA_PDF:
		"https://drive.google.com/file/d/1QAd-2hZDIpWJEnbY8JXkNy_rjoyqLJ-b/preview",
	DLA_FLO_PDF:
		"https://drive.google.com/file/d/13RuRCIOAVeNgIj9NYX-EAyeHu5iWQuMU/preview",
	DEMU_PDF:
		"https://drive.google.com/file/d/1cRr4sBo1Y5O9z4svcn7X-UQ-zFqhNrAj/preview",
	DEWA_PDF:
		"https://drive.google.com/file/d/158eTxpfQc5YTiQFiaf8n-cspZ8eo-JKs/preview",
	DIACID_PDF:
		"https://drive.google.com/file/d/1KWSp5t4JQJPjgq_W96mGV6TczsEYEmMt/preview",
	DEHAZER_PDF:
		"https://drive.google.com/file/d/15-RJZ9_GQaAvJ0BkXoIWzb1dSmrZQ7e7/preview",
	CORRINAC_PDF:
		"https://drive.google.com/file/d/10ciqGRpVSivkZjFO3yd6A2zX10Vh-2Eb/preview",
	COSOL_PDF:
		"https://drive.google.com/file/d/1YanO-DEZXjcLBTpwhBx3nmZULzoCR3tO/preview",
	COP_PDF:
		"https://drive.google.com/file/d/19M128nOMimPvsEDi9fvClShvMlhPwAc6/preview",
	CORRMIT_W2_PDF:
		"https://drive.google.com/file/d/10FpYT4g--3nn9NCdBLNOJZpolJM92400/preview",
	CIC_PDF:
		"https://drive.google.com/file/d/1oqDU43gbUHtRR_Ww4Jgk9YEyWgpM0Jfm/preview",
	BUBBLY_PDF:
		"https://drive.google.com/file/d/1MRWmc_XEyEEvboPZ15fdix1RKwoSItIZ/preview",
	BIOACTICA_PDF:
		"https://drive.google.com/file/d/1_YXUnzUp8tVAWcSWRaBQHkSlL9XI_Jra/preview",
	THERMOPRO_D_PDF:
		"https://drive.google.com/file/d/18L7Vhw-UgKIxE_Dd9c7jb6YGEh4nqRcc/preview",
	BIOREMEDIA_PDF:
		"https://drive.google.com/file/d/1ZtZZQx9jKG6-p-La1sdEj02CqWuVZhHv/preview",
	HP2FCC_PDF:
		"https://drive.google.com/file/d/1TbBRoxV9doRaCLY1qo-UTBKKrDX8xLCr/preview",
	BIOFILM_PDF:
		"https://drive.google.com/file/d/14u7NVUjbk-cAruJIK3drx983T5NWss6s/preview",
	BCA_PDF:
		"https://drive.google.com/file/d/1-KGoUySudBZbZgK8l0kpHs9agHUqQmQg/preview",
	BOILMAX_PDF:
		"https://drive.google.com/file/d/16KTFRqvxPOHBpETkuzv9L2LOwjEVeqvW/preview",
	"13X31_PDF":
		"https://drive.google.com/file/d/1AYUFkgTbNptvGQbDdiFsIgSEX-4eNBBj/preview",
	AQUAOKARE_BCW_PDF:
		"https://drive.google.com/file/d/10ieLgj89T9LkkgRC3pnXZZV2lW9bnuOn/preview",
	ANTIFOAM_PDF:
		"https://drive.google.com/file/d/1J11v7htG4WmPPf1YN1KBOduO7CqBvp-N/preview",
	"3DPP_PDF":
		"https://drive.google.com/file/d/16S5lQKSAyuFf8gxIdj8gNEclV0Hp-zdx/preview",
	BIOP_PDF:
		"https://drive.google.com/file/d/1yMdWML9UAUYvsNTQYYTw3S0xjI3pTru0/preview",
	AQUASCALEOUT_PDF:
		"https://drive.google.com/file/d/1PTz0Zhv6cPdPrzBQELg2j41s1jVK956g/preview",
	INVIUS_PDF:
		"https://drive.google.com/file/d/13hQT3y7c05QTefq0V_CbzqWMyMS81zYZ/view?usp=drive_link",
};
