// pdfRegistry.ts
export const ALL_PDFS: Record<string, any> = {
  BITUMEN_PDF:
    "https://drive.google.com/file/d/10zCWlS6wPiuXQ4oLaiGrd3LYtLmxnOaU/preview",
  VG30_PDF:
    "https://drive.google.com/file/d/16NPtVEIF_FQ3PE8fq4ZDmOqhgGagM2DB/preview",
  VG40_PDF:
    "https://drive.google.com/file/d/1yHnYH3SD4ElVTp3w5EAWmq1GLTQJS4sa/preview",
  GRI_150N_PDF:
    "https://drive.google.com/file/d/1trUa2hqpbdUX_2M_IfPnQC5sEtXeUZo6/preview",
  GRII_150SN_PDF:
    "https://drive.google.com/file/d/1trUa2hqpbdUX_2M_IfPnQC5sEtXeUZo6/preview",
  ATF_PDF:
    "https://drive.google.com/file/d/15WLcZftJDC-mBHhLaH_96JYEkRvswVyV/preview",
  BRF150BS_PDF:
    "https://drive.google.com/file/d/1dP7G6jKTtq4DKQjg5RUxQel_AUar7MTz/preview",
  ELASTO_SUPREME_H_PDF:
    "https://drive.google.com/file/d/1c6yLaEWLgWrFdTqRkr-BGtkINTKDsY6S/preview",
  ELASTO_SUPREME_PDF:
    "https://drive.google.com/file/d/1PCfYmLX1NpYgZXgBqWAWapTfecQndcSi/preview",
  ELASTO710_PDF:
    "https://drive.google.com/file/d/1el_3jRUItWf2zAITd48I2miYgwFLihzg/preview",
  ETHANOL_PDF:
    "https://drive.google.com/file/d/1KCiHAebR2RixzieGsTLxDz3P6VUUKtXR/preview",
  FLAME_PLUS_PDF:
    "https://drive.google.com/file/d/1H7cXRmC5yPutA-huEY5XOiRvbjIAwluF/preview",
  HEXANE_PDF:
    "https://drive.google.com/file/d/1za_EnUkoVu5wRJSreLMjUfoqyGmgdb8B/preview",
  HFHSD_PDF:
    "https://drive.google.com/file/d/1Z2nvVkqHd1Jarv-ACHJSuy7TGs_ZTRF1/preview",
  HSD_PDF:
    "https://drive.google.com/file/d/1Fpq-Ronp4JcuOLkK6h3YgoVR_HCXJYOS/preview",
  JBO_PDF:
    "https://drive.google.com/file/d/1zY_WRZ-doup9fqtdItrWaR06IV-gcMXp/preview",
  LDO_PDF:
    "https://drive.google.com/file/d/1nbRH_ZPY67WdrgG6CLUiePJAeovqLCyT/preview",
  LLDPE_PDF:
    "https://drive.google.com/file/d/1vPHy_mZ6hbDufEeydo_TrM0IHHmbIcYx/preview",
  LPG_PDF:
    "https://drive.google.com/file/d/1n_FEoXe0qLVRayCEN5N9VrZPHmvx5mfE/preview",
  LSFO_LSHSFO_VLSFO_PDF:
    "https://drive.google.com/file/d/17TK8nAw54Rgzg0x9rklX2MiZnMY-mzQV/preview",
  LSHS_PDF:
    "https://drive.google.com/file/d/1uLameSLiEgZugTHIJ-X0Afv9WN5KLqon/preview",
  MS_PDF:
    "https://drive.google.com/file/d/1F1MxlDBQtm3X8_s81FQ4JUzOq6a8WJ5O/preview",
  NAPHTHA_PDF:
    "https://drive.google.com/file/d/1XseSYUB7meiCWuTwdvVvVugiiQ1Ahuq5/preview",
  PPHP_PDF:
    "https://drive.google.com/file/d/1Szsbi6agYX2f43H54bK0UbCbPdGSE_Rg/preview",
  PROPANE_BUTANE_PDF:
    "https://drive.google.com/file/d/109IbTn3Vy9ZyjKyAIwiuJFYnCEJhX3qB/preview",
  SOLVENT_1425_PDF:
    "https://drive.google.com/file/d/1U-krPb89e85GECrMkmc421EmBFtzvJx6/preview",
  SOLVENT_2445_PDF:
    "https://drive.google.com/file/d/12ydV3AOpceFvNKA-bpvk8bVoBU9PCTuW/preview",
  KEROSENE_PDF:
    "https://drive.google.com/file/d/1CVLNw7vucDCnqT-rv1Edsyg_JzmokBCn/preview",
  HOMOPOLYMER_PDF:
    "https://drive.google.com/file/d/15LP01gpzIKYkQ2jF0WPSEmzQu32KgNVz/preview",
  "500N_PDF":
    "https://drive.google.com/file/d/17rwJFvVlmgI3gBCTrASZ9jBpE117PWRi/preview",
  "500SN_PDF":
    "https://drive.google.com/file/d/1PbdiVr_WGyh-RLxDq1RlP7-PQi67NWEf/preview",
  HP_GAS_RAZOR_PDF:
    "https://drive.google.com/file/d/1HI0QV_VElQR64gpIAFnyu2IPLxPWbfn-/preview",
  // PROPYLENE_PDF:
  // 	"https://drive.google.com/file/d/1pAsaBMM8KisOmRT_VL3gOSqy_QQ39qrc/preview",
  CRMB_PDF:
    "https://drive.google.com/file/d/1ToabsezpMbOLN9ZBTZ-05JoQn4iFsgQy/preview",
  DOLPHIN_PDF:
    "https://drive.google.com/file/d/1JOl7vxYKrHVv94Z6hAh_KTbr0GOwGlGw/preview",
  PROPYLENE_PDF:
    "https://drive.google.com/file/d/1fQNv4G6UM4pK1wFLexiFAHlhN5dGXuhJ/preview",

  // R&D MSDS
  HP_DWA_Brouchure:
    "https://drive.google.com/file/d/1fqB1G7xzhFF5RBr3YXA5UIDfi67ldwjs/preview",
  HP_TIC_Brochure:
    "https://drive.google.com/file/d/156lOh5sWBxkoHoxJ4l3GHA7fz10W2SsV/preview",
  "HP_Frost-Free_v2.0_Brochure":
    "https://drive.google.com/file/d/1X4s3pw-8PnLn6-Zwwoesq6HUmyMgajKg/preview",
  HP_Neutmax_Brochure:
    "https://drive.google.com/file/d/1TrFfYOpEWTnvS_RrhyTmlWAkeXENCfr2/preview",
  HP_Bioactiva_Brochure:
    "https://drive.google.com/file/d/1LBfOYN6_muDgS1U--_-ZoLsIxiVProsd/preview",
  HP_DEWA_Brochure:
    "https://drive.google.com/file/d/1PEmb1XpmllEGkPxvPTTLf9uRNpr78nK1/preview",
  HP_JnrPro_brochure:
    "https://drive.google.com/file/d/1mOjHyAK6GE_FH9dquJXI2TKK0jMaBGBe/preview",
  "HP_VisABit_V2.0_Brochure":
    "https://drive.google.com/file/d/1Su1PKUthkFpaVTSxojxEaUyiPmdcyqCQ/preview",
  HP_DLA_Brochure:
    "https://drive.google.com/file/d/1BGbPhHJWZu_vDWFzxQtlUnRGcaRLz0cX/preview",
  "HP_FILMMAX_HT_Brochure-V2":
    "https://drive.google.com/file/d/1Yo36gE3jjzA4OxvC3Tdiarc3HN9FknL-/preview",
  HP_ShinePro_Brochure:
    "https://drive.google.com/file/d/1sffIMVRTT0qSecMcM9E19OWoP7MN5pfX/preview",
  "HP_Thermopro-W_Brochure":
    "https://drive.google.com/file/d/1v-EVT7oUqrN43dZiJjT0YdU0e9P70B8X/preview",
  HP_DEMU_Brochure:
    "https://drive.google.com/file/d/1ByKg2YPGPSfYbX-u_pzCi-YsnIxhAAxZ/preview",
  HP_PPD_ULSD_Brochure:
    "https://drive.google.com/file/d/16e7ebNBNhcz0TJMENDmjhWb-C6L7i4HQ/preview",
  HP_EGIN_Brochure:
    "https://drive.google.com/file/d/14gAFd53JRX4Yy2C6fHWZej3qMjvfzjOf/preview",
  HP_Purus_Brochure:
    "https://drive.google.com/file/d/1mtxrlWSoCBg9IjTdpB4F_NmSsVtp8xS_/preview",
  "HP_CORRMIT_LPG_Brochure-V2":
    "https://drive.google.com/file/d/1fdTDyEn-qhdu1iKWI87Xnr6Cu9weW7yi/preview",
  "HP_Frost-free_Brochure":
    "https://drive.google.com/file/d/1orQ0BPsUiiVI4f8ojqmfgwqZurH60DRX/preview",
  "HP_WMA_Brochure-v3":
    "https://drive.google.com/file/d/1-j8SnjUSd2mm_rtIO-lWNJ1W8-pA5sFv/preview",
  HP2Catalyst_Brouchure:
    "https://drive.google.com/file/d/1rBzRecoo4QFDXF2k34jdT9L80gpTOzYw/preview",
  HP_SolarOKare_Brochure:
    "https://drive.google.com/file/d/1Ju3EM5pKtxnwmdDvgQMcDmyana-rg9fh/preview",
  HP_NanOKoool_Brochure:
    "https://drive.google.com/file/d/14OHd_i3vgYleMxuhgHHGv69KFz_HvwmV/preview",
  HP_3DPP_Brochure:
    "https://drive.google.com/file/d/11wfCGG72nUTN8NbMcxUGwAyBjwf2y8ca/preview",
  HP_FurnOKare_brouchure:
    "https://drive.google.com/file/d/1tDKkW-oVIxjjNXryIs2Eb73Qf8jTFhWk/preview",
  HP_DEHAZER_Brochure:
    "https://drive.google.com/file/d/1X-C5j4JXgqUJOxsd-2tIeRVsy-cHkZ7d/preview",
  HP_BOILMAX_pdf_Brochure:
    "https://drive.google.com/file/d/1-TyPrkG-jDyuDmdGqkVz_77zm7MCVvSB/preview",
  HP_13X31_Brochure:
    "https://drive.google.com/file/d/1SlylGb9WYh_Orb3vJVuXHuK13yPNx42e/preview",
  HP_HYTHERM_Gamma_Brouchure:
    "https://drive.google.com/file/d/1t90f1Egr4kirMtmpLf8lvvz-SN4ML9jD/preview",
  "HP-COP_Brochure":
    "https://drive.google.com/file/d/1HpuWZ6Hs7N7iayD18iQJSvDujQHfuHZc/preview",
  HP_FILMMAX_Brochure:
    "https://drive.google.com/file/d/1dLUiCcoiKhOadLpbLVOQ7jsgoD9xAt3b/preview",
  HP_poWer_100_Brochure:
    "https://drive.google.com/file/d/1xTVnc2yrVBdqSdp7kR0QOIJ11phz8SME/preview",
  "HP_i-COMB_brochure":
    "https://drive.google.com/file/d/1_swhDCqADFjgfo4Up4HkyvIB88AttrQS/preview",
  HP_Invius_Brochure:
    "https://drive.google.com/file/d/1RlJxEA36wmBlmh4DmDXElErdqlFNGeis/preview",
  "HP-Polysano_Broucher":
    "https://drive.google.com/file/d/1n9kXjjLOI0DosU9dhjZ6IqTOO-vKma4e/preview",
  HP_BituLock_brochure:
    "https://drive.google.com/file/d/1jNLv1jS6tjvLa1yFLWVeSByfIuNKDcnu/preview",
  HP_Sweetpro_Brouchure_final:
    "https://drive.google.com/file/d/13n78ptcyxO0rDyPOXldMOek0oqr1L_XU/preview",
  HP_DRA_brouchure:
    "https://drive.google.com/file/d/13dkn9d9rj_9FefOucnbbi2LZPAFPFlY7/preview",
  HP_NanoLite_Brochure:
    "https://drive.google.com/file/d/15EfO3CbVwCaQvqGYy1sYpl1xzWQkq9Ci/preview",
  HP_EasyWash_Brochure:
    "https://drive.google.com/file/d/1J3BZuuJWKC18boDID_3u5SKlyx1jBZfr/preview",
  HP_HYTHERM_Omega_Brouchure:
    "https://drive.google.com/file/d/1oeaQJLh6s0K61xSgs2unN1If9aruwu3W/preview",
  "HP-HYTHERM-Alpha":
    "https://drive.google.com/file/d/10dWYlMhXbwkoqsHyDowpwUnrVzhXYMAM/preview",
  HP_PFT:
    "https://drive.google.com/file/d/1hL9YIHYRihSRpfX-fymSnOXdTkUBqQkf/preview",
  _HP_PPD_Lube_Brochure:
    "https://drive.google.com/file/d/1a4QrzIe_zf_8jYxFMfPdi0osVwc0jFNF/preview",
  HP_Bioremedia_Brochure:
    "https://drive.google.com/file/d/1oywaoZRO79b-oa-fn5Q7v6Yf0RtlQEx0/preview",
  HP_DUCER_NHT_Brochure:
    "https://drive.google.com/file/d/1Y_xLrIxYKkrrl0UBRIyUHSpzZXA66Epi/preview",
  "HP_Frost-Shield_v2.0_Brochure":
    "https://drive.google.com/file/d/1mnuKCZiGub30Qo38aOrfUUZ_6LR98_rR/preview",
  HP_VisABit_Brochure:
    "https://drive.google.com/file/d/1rpsXg-4Z2O33m6sa-Z8snjePWDGZf7yd/preview",
  "HP_Frost-shield_Brochure":
    "https://drive.google.com/file/d/1nh9osWGTxogqINPjQ1mv6tRC6eKceBk9/preview",
  HP_Laundry_Sanitizer_Brochure:
    "https://drive.google.com/file/d/1zLq6HlJ1ZMFAgLQnsJG99zN9-HdDcg9Q/preview",
  HP_ThermoPro_D_Brouchure:
    "https://drive.google.com/file/d/1bgqLW0ejELb5qLIdWy5kIx9LHAWOliIj/preview",
  HP_PCR_HDPE_Brochure:
    "https://drive.google.com/file/d/15vxsPzM9eZ-5cvKRp3S6haXWaVuJAjW8/preview",
  HP_Primer_Brochure:
    "https://drive.google.com/file/d/1yMvenqRFdgPpY87wakds5rTo4BBMimB5/preview",
  "HP-Fuse3D_Product_Brochure":
    "https://drive.google.com/file/d/1c0IkedsPMspntKV3hwEjRErA6S2lrkgK/preview",
  HSPLA_Product_Brochure:
    "https://drive.google.com/file/d/1n9kXjjLOI0DosU9dhjZ6IqTOO-vKma4e/preview",
  HP_AquaScaleout_Brouchure:
    "https://drive.google.com/file/d/1W0Bhleiv51oPuy6usmEg8RBb4uZCS5zI/preview",
  HP_GAS_FLAME_PLUS_Brochure:
    "https://drive.google.com/file/d/11_wyiSNZWGUuBohDXbhrapVPsn6WsMMH/preview",
  HP_GAS_Dolphin_brochure:
    "https://drive.google.com/file/d/1ZJ3vFekQUKy-FfG3xEy6r9JqiiSO9o8q/preview",
  HP_BioFilm_Brochure:
    "https://drive.google.com/file/d/1FZP_J2FzMfw1XRf2wNQV5PwkQbgpmsND/preview",
  "HP_CORRMIT_W_2.0_Brouchure":
    "https://drive.google.com/file/d/1RpAny0GUXAGiZnPdrWOtDgIlo8qfoiCg/preview",
  HP_Bubbly_Brochure:
    "https://drive.google.com/file/d/1EoSoUV6LB5m8XdHVIX2Mfs16hVr7Qs3m/preview",
  HP_SAN_Brochure:
    "https://drive.google.com/file/d/1ixtaXiGDKEdSPVbBBLRvDYxiyNWBY6Dw/preview",
  SEU_NEUTMAX_brochure:
    "https://drive.google.com/file/d/1t4UiNhDMWa1Bl_NkTYt7c70Q8WlDf_En/preview",
  HP_Thermopro_Brochure:
    "https://drive.google.com/file/d/1OKzljw4-kmNEkTaZnY-KpaagBvTwWoUF/preview",
  HP_DUCER_Brochure:
    "https://drive.google.com/file/d/11fZ9YkpdCLf7bykjc_ikwD8szvniYkNT/preview",
  HP_CorrInAc_Flyer:
    "https://drive.google.com/file/d/11zNgnRl9gFohG4g4JCk8RystxgvPZ67j/preview",
  HP_poWer_99_Brochure:
    "https://drive.google.com/file/d/1oDNrqnSTbF8XIdPp20oSIZL5Kz4TSyHl/preview",
  HP_BCA_Brocheure:
    "https://drive.google.com/file/d/1mNL7B-tAlyEM6XLkarnsjYZGktGYJVDs/preview",
  HP_PMA_Brocheure:
    "https://drive.google.com/file/d/1cbqoyyLfntdxuYg5kWlnrE3CN75GrjVt/preview",
  HP_poWer95_Brochure:
    "https://drive.google.com/file/d/1qbWHhQUUfjgQl9cAvV9BQ5cSIvXsH528/preview",
  HP_Diacid_Brouchure:
    "https://drive.google.com/file/d/1oNdWvxUR29xrsTntcbZr0K0F3NyWzKVC/preview",
  "._HP_CIC":
    "https://drive.google.com/file/d/1puXEbpXTFVsJ8930H2AObuD0eofgjQzj/preview",
  HP_Gas_Razor_Brochure:
    "https://drive.google.com/file/d/1tCwmDe1KcxfDGFhJaXzXeRZP4a2t5kh0/preview",
  HP_AquaOkare_Brouchure:
    "https://drive.google.com/file/d/1g1iUb2bnHCg0R0baVIN4tqjFXAeXJG7w/preview",
  HP_Enscour_Brochure:
    "https://drive.google.com/file/d/1dSWS2maNATlIKPCANt8TPhOox-FE0PxW/preview",
  "HP-SolarOKare_V_2.0_Brochure":
    "https://drive.google.com/file/d/18vecW0m3zK7mIqlash3i3zlFYd1um68t/preview",
  "HP-BioP_Product_Brochure":
    "https://drive.google.com/file/d/1aydJdJnHMJvOqRgeDtH1bmxWfB1Uo00c/preview",
  HP_NanOKoat_Brochure:
    "https://drive.google.com/file/d/1mYIU4cTNrv5i4zxXrVjxvVTuLTxYnU8u/preview",
  "HP-AntiFoam_Brochure":
    "https://drive.google.com/file/d/1Gizi3t5MLDYti_CmgESvfpfV5MiCOdPV/preview",

  // Industrial MSDS
  Propylene_Industrial_MSDS:
    "https://drive.google.com/file/d/1yidNRkil-1DD1h_EY_E_GgaMjt4UQjw0/preview",
  JBO_Industrial_MSDS:
    "https://drive.google.com/file/d/19E23Ojz6QjLJNA9cbw1mCOO6j64TG81C/preview",
  FO_Indstrial_MSDS:
    "https://drive.google.com/file/d/1D5D1jfek-ULv6aTyFH2hE9I9aSHLkv1_/preview",
  Hexane_Industrial_MSDS:
    "https://drive.google.com/file/d/1wvqbxmJRtCXiX8Q6ZXBlUendI8zR0hM1/preview",
  LDO_Industrial_MSDS:
    "https://drive.google.com/file/d/1uudzCAD-k1_aU6dLr5uvo5hHdQwx0Jfv/preview",
  HSD_Industrial_MSDS:
    "https://drive.google.com/file/d/1YAdoTP4S6kNTtDhjsBgTykxw0Qj1KaSW/preview",
  Naptha_Industrial_MSDS:
    "https://drive.google.com/file/d/1w7C-CxQJmSNx7KWP-YURyg4vobTxqKNC/preview",
  LSHS_Industrial_MSDS:
    "https://drive.google.com/file/d/12sPqvA_-uhaH4sj1y3b1XXyVktkoduDu/preview",
  MS_Industrial_MSDS:
    "https://drive.google.com/file/d/1OCSVeU8q1v6fw8jIpWAQIi_rZRrUN_ff/preview",
  VG30_Industrial_MSDS:
    "https://drive.google.com/file/d/1HqFezviVgayhOlfBOyV9o62EV5h-93dS/preview",
  VG40_Industrial_MSDS:
    "https://drive.google.com/file/d/11r8-l_eOd2qyBZG0LJTyhyOajbIB-gIa/preview",
  SKO_Industrial_MSDS:
    "https://drive.google.com/file/d/1rr21StbQAmB7iepokMGnoSedt-zoeVwC/preview",
  Solvent1425_Industrial_MSDS:
    "https://drive.google.com/file/d/1ggQpw-wcu43N1LmYQ2YCx9Mv3qFY5VZM/preview",
  Solvent2445_Industrial_MSDS:
    "https://drive.google.com/file/d/13koacg7Nk35Au-I6_8KSOKuX-n4et46k/preview",
  Sulpher_Industrial_MSDS:
    "https://drive.google.com/file/d/11H5s8yNHtipd6jRHmPpWG8CYg6-2o8HW/preview",
  VG10_Industrial_MSDS:
    "https://drive.google.com/file/d/13uxy6n93CIcCPYICzGYFUk8nneYcX7kW/preview",
  FO380_Industrial_MSDS:
    "https://drive.google.com/file/d/1nBdbQnZV9AmNiZ1VYzmi7IY8bqPKGXFm/preview",
  F01019S_MS_PDF:
    "https://drive.google.com/file/d/1doOV0ycg189-hhKkDeB2CvXF-6iTvTVE/preview",
  HM120A_MS_PDF:
    "https://drive.google.com/file/d/1DVWoqm8DmUa5OQ-6qBODYuzy1Q0ZmHxH/preview",
  F02020_MS_PDF:
    "https://drive.google.com/file/d/1FePjnZIwJeD3se9aWeew3xqs6zwTQedc/preview",
  M50200_MS_PDF:
    "https://drive.google.com/file/d/1A2JPUdEzCWXGTFIOpEBlqWQtT53y-drC/preview",
  HR033_MS_PDF:
    "https://drive.google.com/file/d/18qHS7fTcEdHsdsvaM1bhjXX9lIy_Jid1/preview",
};

// CBFS
// VG10-161.8
// VG30-161.8
// VG40 Super
