export const ALL_IMAGES = {
	MASTER_LOGO: require("@/assets/images/Master_Logo.png"),
	LIQUID_ICON: require("@/assets/images/icons/Location.png"),
	LOCATION_ICON: require("@/assets/images/icons/Location.png"),
	CYLINDER_ICON: require("@/assets/images/icons/cylinder.png"),
	BULK_TANK_ICON: require("@/assets/images/icons/bulk_tanker.png"),
	HAPPINESS_ICON: require("@/assets/images/icons/DeliveringHappiness.png"),
	SOLVENTS_ICON: require("@/assets/images/icons/PMB.png"),
	COMPASS_ICON: require("@/assets/images/icons/compass-solid.png"),
	CALCULATOR_ICON: require("@/assets/images/icons/calculator-solid.png"),
	BROUCHER_ICON: require("@/assets/images/icons/Broucher.png"),
	SHIELD_ICON: require("@/assets/images/icons/shield-solid.png"),
	FUEL_ICON: require("@/assets/images/icons/fuel_icon.png"),
	OIL_ICON: require("@/assets/images/icons/oilcan-solid.png"),
	INDUSTRIAL_ICON: require("@/assets/images/icons/CRMB.png"),
	DRUMS_ICON: require("@/assets/images/icons/Drums.png"),
	WATER_ICON: require("@/assets/images/icons/Waterproofing.png"),
	ROAD_ICON: require("@/assets/images/icons/road-construction.png"),
	FIRE_ICON: require("@/assets/images/icons/fire-solid.png"),
};
